title: Singapore Government ICT&SS Policy Reform
url: https://im8.tech.gov.sg
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#70389b"
  secondary-color: "#0061af"
  media-colors:
    - title: media-color-one
      color: "#a7c539"
    - title: media-color-two
      color: "#00984e"
    - title: media-color-three
      color: "#00c0f3"
    - title: media-color-four
      color: "#0061af"
    - title: media-color-five
      color: "#b41e8e"
description: A site of the Singapore Government. The ICT&SS Policy Reform is an
  effort to transform the policy controls to be lean, relevant and effective. It
  enables differentiated treatment for systems of different risk materiality
  levels.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.d3ech1ul6ye0y6.amplifyapp.com
prod: https://master.d2kzw23lpbfro.amplifyapp.com
facebook-pixel: ""
resources_name: resource-room
shareicon: /images/isomer-logo.svg
is_government: true
google_analytics_ga4: ""
linkedin-insights: ""
